apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  INVENTORY_DB_USER: bml0aGlu
  INVENTORY_DB_PASSWORD: cGFzc3dvcmQ=
  INVENTORY_DB_NAME: aW52ZW50b3J5LWRi
  ORDER_DB_USER: bml0aGlu
  ORDER_DB_PASSWORD: cGFzc3dvcmQ=
  ORDER_DB_NAME: b3JkZXJzLWRi
  GIT_PASSWORD: Z2l0aHViX3BhdF8xMUJBV1YzSUEwZG1sNkowc1VxaTlHX0NJRTZuMkRCbWtTYjRJbGprN2ZlQjBwVVI0SENzVDNWUEZuYVBJTlVFVGNZTFNKUTNEWVpZRnFOZ2xt



#WARNING: You should not place the username and password in the version control repository or anywhere else in plain text.
#Instead, use the Services Tool Window -> Kubernetes -> <Desired Cluster> -> Configuration -> <right-click on Secrets> -> Create New Secret...
