apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      name: order-service
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: nithinreddyyelluri/ecommerce-order-service:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "400Mi"
              cpu: "200m"
            requests:
              memory: "200Mi"
              cpu: "100m"
          ports:
            - containerPort: 9040
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: DB_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: ORDER_DB_SERVICE
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: ORDER_DB_NAME
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: ORDER_DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: ORDER_DB_PASSWORD
            - name: KAFKA_BROKER
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: KAFKA_BROKER


---

apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - port: 9040
      targetPort: 9040

      