apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod
  labels:
    app: my-app
    env: dev
spec:
  containers:
    - name: my-nginx-container
      image: nginx:latest
      resources:
        limits:
          cpu : "500m"
          memory: "128Mi"
      ports:
        - containerPort: 80