apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql-db
  serviceName: headless-service-sql
  template:
    metadata:
      name: mysql-db
      labels:
        app: mysql-db
    spec:
      containers:
        - name: mysql-container
          image: mysql:latest
          ports:
            - containerPort: 3306 
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "password"
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard
    
---

apiVersion: v1
kind: Service
metadata:
  name: headless-service-sql
spec:
  clusterIP: None
  selector:
    app: mysql-db
  ports:
    - port: 2999
      targetPort: 3306
  
