apiVersion: v1
kind: Namespace
metadata:
  name: dev

---

apiVersion: v1
kind: Namespace
metadata:
  name: prod

---

apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-app
  namespace: dev
spec:
  containers:
    - name: my-app-container
      image: nginx
      env:
        - name: ENV
          value: "dev"

---

apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-app
  namespace: prod
spec:
  containers:
    - name: my-app-container
      image: nginx
      env:
        - name: ENV
          value: "prod"
