spring.application.name=currencyConversion


Currency.base.url=https://api.freecurrencyapi.com/
Currency.api.key=fca_live_3CkSTA3N30D9q5xiamTcUEaxGwNMEqvDrsI7keZY

#?apikey=fca_live_3CkSTA3N30D9q5xiamTcUEaxGwNMEqvDrsI7keZY&currencies=INR&base_currency=BGN
