spring:
  application:
    name: spring-ai-demo
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen3:14b
          temperature: 0.9
      embedding:
        options:
          model: nomic-embed-text
    vectorstore:
      pgvector:
        initialize-schema: true
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            table-name: chat_memory

  datasource:
    url: jdbc:postgresql://localhost:5434/my-test-vector-db?timeZone=Asia/Kolkata
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        jdbc:
          timezone: Asia/Kolkata

logging:
  level:
    org.springframework.ai:
      chat.client: DEBUG
