spring.application.name=prod-ready-features

spring.datasource.url=jdbc:mysql://localhost:3306/prod-ready-features?useSSL=false
spring.datasource.username=root
spring.datasource.password=Nithinreddy9491$

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql

spring.devtools.restart.enabled=true
spring.devtools.restart.exclude=com/nithin/prod_ready_features/dto/**
#spring.devtools.restart.pollInterval=20 (ms)used to set time period fater which devtools can poll for changes
#spring.devtools.restart.quietPeriod=10



