spring:
  application:
    name: Poem-GPT

  autoconfigure:
    exclude:
      - org.springframework.ai.model.openai.autoconfigure.OpenAiChatAutoConfiguration
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen3:14b
          temperature: 0.9

    openai:
      chat:
        enabled: false
