spring:
  application:
    name: vibeMatcher

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama-3.3-70b-versatile
      embedding:
        options:
          model: nomic-embed-text
    vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: 768
  datasource:
    url: jdbc:postgresql://localhost:9000/nithin
    username: nithin
    password: password
    driver-class-name: org.postgresql.Driver


