spring.application.name=springbootweb

spring.h2.console.enabled=true

spring.datasource.url=jdbc:h2:file:/Users/Admin/Documents/springfiledb/db
spring.datasource.username=nithin
spring.datasource.password=Nithin123
spring.jpa.hibernate.ddl-auto=update