spring:
  application:
    name: config-server


  cloud:
    config:
      server:
        git:
          uri: https://github.com/yellurinithinreddy/config-server
          username: yellurinithinreddy
          password: ${GIT_PASSWORD}
          default-label: main
server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761







